services:
  speaches:
    image: ghcr.io/speaches-ai/speaches:latest-cuda
    container_name: speaches
    ports:
      - "8885:8000"
    volumes:
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
      - ./audio:/app/audio  # Mount local audio files
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  hf-hub-cache:
